# Generated by Django 4.2.5 on 2023-10-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=20)),
                ('pertenece_a', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=10)),
                ('unidades', models.IntegerField()),
            ],
        ),
    ]
