# Generated by Django 4.2.5 on 2023-09-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0005_alter_personal_apellido_emergencia_alter_personal_cp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fecha_nacimiento',
            field=models.CharField(default='valor_predeterminado', max_length=10),
        ),
    ]
