# Generated by Django 4.2.5 on 2023-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0008_alter_personal_direccion_alter_personal_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='direccion',
            field=models.CharField(default='asd', max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='mail',
            field=models.EmailField(default='asd', max_length=70),
        ),
    ]
