# Generated by Django 4.2.5 on 2023-09-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0017_alter_seller_servicio_1_alter_seller_servicio_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='cotacto_resonsable',
            new_name='contacto_resonsable',
        ),
    ]
