# Generated by Django 4.2.5 on 2023-09-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0002_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='mail',
            field=models.EmailField(max_length=70),
        ),
    ]
