# Generated by Django 4.2.5 on 2023-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0006_alter_personal_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fecha_nacimiento',
            field=models.CharField(max_length=10),
        ),
    ]
