# Generated by Django 4.2.5 on 2023-09-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0013_alter_personal_apellido_emergencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='apellido_emergencia',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='personal',
            name='numero_contacto_emergencia',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='personal',
            name='vinculo',
            field=models.CharField(max_length=15),
        ),
    ]
