# Generated by Django 4.2.5 on 2023-09-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0014_alter_personal_apellido_emergencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='numero_contacto_emergencia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personal',
            name='permisos',
            field=models.CharField(default='a', max_length=15),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sector',
            field=models.CharField(default='a', max_length=15),
        ),
    ]
