# Generated by Django 4.2.5 on 2023-09-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0015_alter_personal_numero_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='permisos',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sector',
            field=models.CharField(max_length=15),
        ),
    ]
