# Generated by Django 4.2.5 on 2023-10-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0019_producto_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
