# Generated by Django 4.2.5 on 2023-10-04 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0020_delete_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
